add appfilter xml check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,18 +17,56 @@ permissions:
   contents: read
   pages: write
   id-token: write
+  pull-requests: write  # Required to comment on PRs
   
-concurrency:
-  group: 'pages'
-  cancel-in-progress: true
-
 jobs:
+  parse_appfilter:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request_target'
+    concurrency:
+      group: ${{ github.workflow }}-${{ github.event.pull_request.user.login }}/${{ github.event.pull_request.head.ref }}
+      cancel-in-progress: true
+    steps:
+      - name: Checkout Repository ${{ github.event.pull_request.user.login }}/${{ github.event.pull_request.head.ref }}
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+          sparse-checkout: |
+            newicons/appfilter.xml
+          sparse-checkout-cone-mode: false
+      - name: Install xmllint
+        shell: bash
+        run: |
+          sudo apt update
+          sudo apt install -y libxml2-utils
+      - name: Validate appfilter.xml
+        id: validate
+        run: |            
+          if ! PARSE_OUTPUT=$(xmllint --noout newicons/appfilter.xml 2>&1) ; then
+            echo "Parsing appfilter.xml failed."
+            echo -e "Parsing of 'newicons/appfilter.xml' failed. Please fix the XML syntax errors. \n \`\`\` \n $PARSE_OUTPUT \n \`\`\`" >> comment_markdown.md
+            exit 1
+          else
+            echo "Parsing succeeded."
+          fi
+      - name: Post failure comment to PR
+        if: failure()
+        run: |
+          gh pr comment ${{ github.event.pull_request.number }} --body-file comment_markdown.md
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   parse_and_combine:
+    needs: parse_appfilter
+    if: '!failure()'
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
-    
+    concurrency:
+      group: 'pages'
+      cancel-in-progress: true
+
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
